In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib
from wordcloud import WordCloud

In [2]:
#Importing Airbnb dataset from excel
data = pd.read_excel("./Airbnb_V1_clean.xlsx")

In [3]:
data.head(5)

,id,name,description,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
0,2595,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",2845,Jennifer,2008-09-09,"New York, New York, United States",within a day,0.83,0.24,...,48,94.0,9.0,9.0,10.0,10.0,10.0,9.0,2,0.37
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",4869,LisaRoxanne,2008-12-07,"New York, New York, United States",within an hour,0.94,0.96,...,349,89.0,8.0,9.0,9.0,9.0,9.0,9.0,1,4.82
2,5121,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,7356,Garon,2009-02-03,"New York, New York, United States",NaN,NaN,1.00,...,50,90.0,8.0,8.0,10.0,10.0,9.0,9.0,1,0.36
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,7378,Rebecca,2009-02-03,"New York, New York, United States",within a few hours,1.00,NaN,...,1,97.0,10.0,10.0,10.0,10.0,8.0,10.0,1,0.01
4,5178,Large Furnished Room Near B'wayã€€,Please donâ€™t expect the luxury here just a b...,8967,Shunichi,2009-03-03,"New York, New York, United States",within a few hours,1.00,1.00,...,473,84.0,9.0,7.0,9.0,9.0,10.0,9.0,1,3.42

In [4]:
# Dataset description
data.describe().T

,count,mean,std,min,25%,50%,75%,max
id,45756.0,2.309535e+07,1.382572e+07,2595.00000,1.061546e+07,2.224709e+07,3.593987e+07,4.533040e+07
host_id,45756.0,8.437272e+07,9.920451e+07,2438.00000,9.250917e+06,3.726838e+07,1.359344e+08,3.665571e+08
host_response_rate,21908.0,8.729870e-01,2.599574e-01,0.00000,9.000000e-01,1.000000e+00,1.000000e+00,1.000000e+00
host_acceptance_rate,29228.0,8.048460e-01,2.771249e-01,0.00000,7.200000e-01,9.400000e-01,1.000000e+00,1.000000e+00
latitude,45756.0,4.072963e+01,5.502481e-02,40.50868,4.069003e+01,4.072455e+01,4.076316e+01,4.091214e+01
longitude,45756.0,-7.395075e+01,4.777557e-02,-74.23986,-7.398315e+01,-7.395539e+01,-7.393399e+01,-7.371299e+01
accommodates,45756.0,2.773429e+00,1.818494e+00,0.00000,2.000000e+00,2.000000e+00,4.000000e+00,1.600000e+01
bedrooms,41349.0,1.292945e+00,6.837461e-01,1.00000,1.000000e+00,1.000000e+00,1.000000e+00,2.100000e+01
beds,45251.0,1.511083e+00,1.100529e+00,0.00000,1.000000e+00,1.000000e+00,2.000000e+00,4.000000e+01
price,45756.0,1.495575e+02,3.153679e+02,0.00000,6.500000e+01,1.000000e+02,1.600000e+02,1.000000e+04
minimum_nights,45756.0,8.767703e+00,2.393868e+01,1.00000,2.000000e+00,3.000000e+00,6.000000e+00,1.250000e+03
maximum_nights,45756.0,4.840352e+04,1.004022e+07,1.00000,2.900000e+01,3.650000e+02,1.125000e+03,2.147484e+09
availability_30,45756.0,9.852959e+00,1.271972e+01,0.00000,0.000000e+00,0.000000e+00,2.600000e+01,3.000000e+01
availability_365,45756.0,1.207407e+02,1.426536e+02,0.00000,0.000000e+00,5.200000e+01,2.510000e+02,3.650000e+02
number_of_reviews,45756.0,2.256019e+01,4.649167e+01,0.00000,1.000000e+00,4.000000e+00,2.100000e+01,7.460000e+02
review_scores_rating,34054.0,9.387869e+01,9.323709e+00,20.00000,9.200000e+01,9.700000e+01,1.000000e+02,1.000000e+02
review_scores_accuracy,34024.0,9.603221e+00,9.065867e-01,2.00000,9.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_cleanliness,34037.0,9.272850e+00,1.132084e+00,2.00000,9.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_checkin,34009.0,9.728836e+00,7.907243e-01,2.00000,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_communication,34029.0,9.730642e+00,8.168515e-01,2.00000,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_location,34006.0,9.597189e+00,7.895862e-01,2.00000,9.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_value,34007.0,9.387950e+00,9.794810e-01,2.00000,9.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01
calculated_host_listings_count,45756.0,5.964813e+00,2.224022e+01,1.00000,1.000000e+00,1.000000e+00,2.000000e+00,2.380000e+02
reviews_per_month,35123.0,8.839174e-01,1.270743e+00,0.01000,1.200000e-01,3.600000e-01,1.160000e+00,4.406000e+01

In [5]:
# Columns with number and percentage of missing data
percentage_missing_data = pd.DataFrame([data.isnull().sum(), data.isnull().sum() * 100.0/data.shape[0]]).T
percentage_missing_data.columns = ['No. of Missing Data', 'Percentage of Missing data']
percentage_missing_data

,No. of Missing Data,Percentage of Missing data
id,0.0,0.000000
name,21.0,0.045896
description,1349.0,2.948247
host_id,0.0,0.000000
host_name,15.0,0.032783
host_since,14.0,0.030597
host_location,139.0,0.303785
host_response_time,23848.0,52.119941
host_response_rate,23848.0,52.119941
host_acceptance_rate,16528.0,36.122039
host_is_superhost,14.0,0.030597
host_verifications,0.0,0.000000
host_has_profile_pic,14.0,0.030597
host_identity_verified,14.0,0.030597
neighbourhood_cleansed,0.0,0.000000
neighbourhood_group_cleansed,0.0,0.000000
latitude,0.0,0.000000
longitude,0.0,0.000000
property_type,0.0,0.000000
room_type,0.0,0.000000
accommodates,0.0,0.000000
bathrooms_text,0.0,0.000000
bedrooms,4407.0,9.631524
beds,505.0,1.103680
amenities,0.0,0.000000
price,0.0,0.000000
minimum_nights,0.0,0.000000
maximum_nights,0.0,0.000000
availability_30,0.0,0.000000
availability_365,0.0,0.000000
number_of_reviews,0.0,0.000000
review_scores_rating,11702.0,25.574788
review_scores_accuracy,11732.0,25.640353
review_scores_cleanliness,11719.0,25.611942
review_scores_checkin,11747.0,25.673136
review_scores_communication,11727.0,25.629426
review_scores_location,11750.0,25.679692
review_scores_value,11749.0,25.677507
calculated_host_listings_count,0.0,0.000000
reviews_per_month,10633.0,23.238482

In [6]:
# Processing 'host_since' columns
data['host_since']= pd.to_datetime(data['host_since'])
data['host_since_year']=pd.DatetimeIndex(data['host_since']).year

In [7]:
# Binning 'host_since' columns
cut_labels_hyear = ['2008-2010', '2010-2012', '2012-2014', '2014-2016','2016-2018','2018-2020']
cut_bins_hyear = [2008.0, 2010.0, 2012.0, 2014.0, 2016.0, 2018.0, 2020.0]
data['binned_hyear'] = pd.cut(data['host_since_year'], bins=cut_bins_hyear, labels=cut_labels_hyear, include_lowest= True)

In [8]:
# Deleting rows with null values
data = data.dropna(axis=0, subset=['host_since'])

In [9]:
# Counting number of elements in 'host_verifications' columns
host_verifications_count = []
for i in data["host_verifications"].items():
    host_verifications_count.append(i[1].count(',')+1)

data["host_verifications_count"] = host_verifications_count

In [10]:
# Binning 'host_verifications' columns
labels_host_verifications_count = ['0 to 4','5 to 8','9 above']
bins_host_verifications_count = [0,4,8,np.inf]
data['binned_host_verifications_count'] = pd.cut(data['host_verifications_count'], bins_host_verifications_count, labels=labels_host_verifications_count, include_lowest= True)

In [11]:
data['binned_host_verifications_count'].value_counts()

5 to 8     27911
0 to 4     15302
9 above     2529
Name: binned_host_verifications_count, dtype: int64

In [12]:
# Binning 'accommodates' columns
bins_accomodate = [0, 1, 2, 3, 4, 5, 6, np.inf]
labels_accomodate =[1,2,3,4,5,6,'7 above']
data['binned_accomodate'] = pd.cut(data['accommodates'], bins_accomodate, labels=labels_accomodate)

In [13]:
data['binned_accomodate'].value_counts()

2          21274
1           7516
4           6837
3           4804
6           2075
5           1715
7 above     1515
Name: binned_accomodate, dtype: int64

In [14]:
# Replacing null values with 0
data['bedrooms'] = data['bedrooms'].replace(np.nan, 0)
data['beds'] = data['beds'].replace(np.nan, 0)

In [15]:
# Binning 'bedrooms' columns
bins_bedrooms = [0, 1, 2, 3, 4, 5,np.inf]
labels_bedrooms =[1,2,3,4,5,'5 above']
data['binned_bedrooms'] = pd.cut(data['bedrooms'], bins_bedrooms, labels=labels_bedrooms, include_lowest= True)

In [16]:
# Binning 'beds' columns
bins_beds = [0,1, 2, 3, 4, np.inf]
labels_beds =[1,2,3,4,'5 above']
data['binned_beds'] = pd.cut(data['beds'], bins_beds, labels=labels_beds, include_lowest= True)

In [17]:
# Binning 'price' columns
labels_price = ['<=100', '>100']
bins_price = [0, 100.00,np.inf]
data['binned_price'] = pd.cut(data['price'], bins=bins_price, labels=labels_price, include_lowest= True)

In [18]:
data['price'].median()

100.0

In [19]:
data[['price','binned_price']].head()

   price binned_price
0  175.0         >100
1   76.0        <=100
2   60.0        <=100
3  175.0         >100
4   79.0        <=100

In [20]:
data['binned_price'].value_counts()

<=100    23956
>100     21786
Name: binned_price, dtype: int64

In [21]:
# Counting number of elements in 'amenities' columns
amenities_count = []
for i in data["amenities"].items():
    amenities_count.append(i[1].count(',')+1)

data["amenities_count"] = amenities_count

In [22]:
# Binning 'amenities' columns
labels_amenities_count = ['0 to 10','11 to 20','21 to 30','31 to 40','41 to 50','51 to 60','60 above']
bins_amenities_count = [0,10,20,30,40,50,60,np.inf]
data['binned_amenities_count'] = pd.cut(data['amenities_count'], bins_amenities_count, labels=labels_amenities_count, include_lowest= True)

In [23]:
# Splitting column 'bathrooms_text' into 'bathrooms_count' and 'bathrooms_type'
data[['bathrooms_count','bathrooms_type']] = pd.DataFrame([x.split(' ') for x in data['bathrooms_text'].tolist()])

In [24]:
data["bathrooms_count"].unique()

array(['1', '', '1.5', '0.5', '2', '3.5', '3', '2.5', '0', '5', '4.5',
       '5.5', '4', '15.5', '6', '8', '6.5', '7.5', '7', nan], dtype=object)

In [25]:
data["bathrooms_type"].unique()

array(['bath', '', 'baths', 'shared', 'private', 'Shared', 'Private', nan],
      dtype=object)

In [26]:
# Replacing nan and spaces with 0:
data['bathrooms_count'] = data['bathrooms_count'].replace(np.nan, 0)
data['bathrooms_count'] = data['bathrooms_count'].replace('', 0)
data['bathrooms_type'] = data['bathrooms_type'].replace('', 0)

In [27]:
data["bathrooms_count"] = data.bathrooms_count.astype(float)

In [28]:
# Binning 'bathrooms_type' columns
value_dict_bathrooms_type  = {'bath':'Private','private':'Private','Private':'Private','baths':'Shared','shared':'Shared','Shared':'Shared',0:'Shared'}
data["binned_bathrooms_type"] = data["bathrooms_type"].replace(value_dict_bathrooms_type)

In [29]:
# Binning 'bathrooms_count' columns
labels_bathrooms_count = ['0 to 1', '1.5 to 2', '2.5 to 3', '3.5 to 4','4 above']
bins_bathrooms_count = [0, 1.0, 2.0, 3.0, 4.0, np.inf]
data['binned_bathrooms_count'] = pd.cut(data['bathrooms_count'], bins=bins_bathrooms_count, labels=labels_bathrooms_count, include_lowest= True)

In [30]:
# Replacing na with median:
data['review_scores_rating'] = data['review_scores_rating'].fillna(data['review_scores_rating'].median())
data['review_scores_accuracy'] = data['review_scores_accuracy'].fillna(data['review_scores_accuracy'].median())
data['review_scores_cleanliness'] = data['review_scores_cleanliness'].fillna(data['review_scores_cleanliness'].median())
data['review_scores_checkin'] = data['review_scores_checkin'].fillna(data['review_scores_checkin'].median())
data['review_scores_communication'] = data['review_scores_accuracy'].fillna(data['review_scores_accuracy'].median())
data['review_scores_location'] = data['review_scores_accuracy'].fillna(data['review_scores_accuracy'].median())
data['review_scores_value'] = data['review_scores_value'].fillna(data['review_scores_value'].median())

In [31]:
# Binning 'availability_365' columns
cut_labels_avail = ['Less than 2 months', '2 - 4 months', '4 - 6 months', '6 - 8 months','8 - 10 months','More than 10 months']
cut_bins_avail = [0, 60, 120, 180, 240, 300, 366]
data['binned_avail365'] = pd.cut(data['availability_365'], bins=cut_bins_avail, labels=cut_labels_avail, include_lowest= True)

In [32]:
# Binning 'number_of_reviews' columns
cut_labels_review = ['None', '1 - 5 reviews', 'More than 5 reviews']
cut_bins_review = [0, 1, 5, 746]
data['binned_no_of_reviews'] = pd.cut(data['number_of_reviews'], bins=cut_bins_review, labels=cut_labels_review, include_lowest= True)

In [33]:
# Binning 'review_scores_rating' columns
cut_labels_review_rat = ['<=90', '>90']
cut_bins_review_rat = [0, 90, 100]
data['binned_review_rating'] = pd.cut(data['review_scores_rating'], bins=cut_bins_review_rat, labels=cut_labels_review_rat, include_lowest= True)

In [34]:
# Binning 'review_scores_accuracy' columns
cut_labels_review_acc = ['<=9', '>9']
cut_bins_review_acc = [0, 9, 10]
data['binned_review_acc'] = pd.cut(data['review_scores_accuracy'], bins=cut_bins_review_acc, labels=cut_labels_review_acc, include_lowest= True)

In [35]:
# Binning 'review_scores_cleanliness' columns
cut_labels_review_clean = ['<=9', '>9']
cut_bins_review_clean = [0, 9, 10]
data['binned_review_clean'] = pd.cut(data['review_scores_cleanliness'], bins=cut_bins_review_clean, labels=cut_labels_review_clean, include_lowest= True)

In [36]:
# Binning 'review_scores_checkin' columns
cut_labels_review_check = ['<=9', '>9']
cut_bins_review_check = [0, 9, 10]
data['binned_review_checkin'] = pd.cut(data['review_scores_checkin'], bins=cut_bins_review_check, labels=cut_labels_review_check, include_lowest= True)

In [37]:
# Binning 'review_scores_communication' columns
cut_labels_review_comm = ['<=9', '>9']
cut_bins_review_comm = [0, 9, 10]
data['binned_review_comm'] = pd.cut(data['review_scores_communication'], bins=cut_bins_review_comm, labels=cut_labels_review_comm, include_lowest= True)

In [38]:
# Binning 'review_scores_location' columns
cut_labels_review_loc = ['<=9', '>9']
cut_bins_review_loc = [0, 9, 10]
data['binned_review_loc'] = pd.cut(data['review_scores_location'], bins=cut_bins_review_loc, labels=cut_labels_review_loc, include_lowest= True)

In [39]:
# Binning 'review_scores_value' columns
cut_labels_review_val = ['<=9', '>9']
cut_bins_review_val = [0, 9, 10]
data['binned_review_ val'] = pd.cut(data['review_scores_value'], bins=cut_bins_review_val, labels=cut_labels_review_val, include_lowest= True)

In [40]:
# Binning 'calculated_host_listings_count' columns
cut_labels_host_list_count = ['Single', 'Multiple']
cut_bins_host_list_count = [0, 1, 239]
data['binned_host_list_count'] = pd.cut(data['calculated_host_listings_count'], bins=cut_bins_host_list_count, labels=cut_labels_host_list_count, include_lowest= True)

In [42]:
data.to_csv('./Airbnb_V1_preprocessedv1.csv')

In [43]:
data['binned_host_verifications_count'].head()

0    9 above
1     5 to 8
2     5 to 8
3     0 to 4
4     0 to 4
Name: binned_host_verifications_count, dtype: category
Categories (3, object): [0 to 4 < 5 to 8 < 9 above]